version: 0.0.3.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

environment:
  KEY_1CV8T:
    secure: OolAVEKkEg1cGCpG/VK2FaM0LWrPgMR/Kn4nTLYyKR0=
  APPVEYOR_RDP_PASSWORD:
    secure: u2GcBSeki25Cko8QoBZKlA==

install:
  - git clone -q --branch=platform https://github.com/lintest/tools1c.git bin
  - cd bin
  - 7z x tools1c.part01.rar -p%KEY_1CV8T%
  - cd ..

build_script:
  - ps: Set-Content -Path app_port.txt -Value ([uri] $env:APPVEYOR_API_URL).Port
  - mkdir database
  - bin\1cv8t.exe CREATEINFOBASE File=%CD%/database
  - bin\1cv8ct.exe ENTERPRISE /F %CD%/database /Execute VanessaExt.epf /C autotest
  - ps: if (!(Test-Path success.txt)) { throw "Имеются ошибки" }

artifacts:
  - path: autotest.log
    name: autotest log

  - path: app_port.txt
    name: app port
