version: 0.0.1.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

environment:
  URL_1CV8T:
    secure: z47uplaqZaQ0ZkroXy0GP00nv6ACPwovtb+EjfPgpS0IlWM6VQd+8apwLfqT9ndX

build_script:
  - powershell -File appveyor.ps1
  - echo Create infobase
  - mkdir testbase
  - bin\1cv8ct.exe CREATEINFOBASE File=%APPVEYOR_BUILD_FOLDER%\testbase
  - echo Load config...
  - bin\1cv8t.exe DESIGNER /F %APPVEYOR_BUILD_FOLDER%\testbase /LoadConfigFromFiles %APPVEYOR_BUILD_FOLDER%\config /UpdateDBCfg
  - echo Process autotest...
  - bin\1cv8ct.exe ENTERPRISE /F %APPVEYOR_BUILD_FOLDER%\testbase
  - echo Autotest finished

cache:
  - 1cv8.zip

artifacts:
  - path: autotest.log
    name: autotest log
