version: 0.0.2.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

environment:
  URL_1CV8T:
    secure: z47uplaqZaQ0ZkroXy0GP00nv6ACPwovtb+EjfPgpS1UVp1iZSkRJGz8uOWarUXi

build_script:
  - ps: Add-AppveyorMessage "Simple message" -Category Error -Details "Детали ошибки"
  - ps: Add-AppveyorCompilationMessage "Error" -Category Error
  - ps: if (!(Test-Path appveyor.ps1)) { throw "Выход с ошибкой" }
  - ps: if (!(Test-Path success.txt)) { throw "Выход с ошибкой" }
  - powershell -File appveyor.ps1
  - 7z x 1cv8t.7z
  - mkdir database
  - bin\1cv8t.exe CREATEINFOBASE File=%CD%/database
  - bin\1cv8t.exe DESIGNER /F %CD%/database /LoadConfigFromFiles %CD%/config /UpdateDBCfg
  - bin\1cv8ct.exe ENTERPRISE /F %CD%/database /C %CD%/autotest.epf
  - ps: Add-AppveyorTest -Name "Test A" -Filename autotest.epf -Outcome Passed -Duration 1000

cache:
  - 1cv8t.7z

artifacts:
  - path: autotest.log
    name: autotest log

  - path: app_port.txt
    name: app port
