version: 0.0.2.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

environment:
  URL_1CV8T:
    secure: z47uplaqZaQ0ZkroXy0GP00nv6ACPwovtb+EjfPgpS0IlWM6VQd+8apwLfqT9ndX

build_script:
  - powershell -File appveyor.ps1
  - echo Create infobase
  - mkdir database
  - bin\1cv8t.exe CREATEINFOBASE File=%CD%/database
  - echo Load config...
  - bin\1cv8t.exe DESIGNER /F %CD%/database /LoadConfigFromFiles %CD%/config /UpdateDBCfg
  - echo Process autotest...
  - bin\1cv8ct.exe ENTERPRISE /F %CD%/database /C %CD%/autotest.epf
  - echo Autotest finished

cache:
  - 1cv8.zip

artifacts:
  - path: autotest.log
    name: autotest log
