version: 0.0.3.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

environment:
  URL_1CV8T:
    secure: z47uplaqZaQ0ZkroXy0GP00nv6ACPwovtb+EjfPgpS1UVp1iZSkRJGz8uOWarUXi
  URL_1CV8L1:
    secure: z47uplaqZaQ0ZkroXy0GP0FOVp3qut62cSHHfMDZqwC2UPYsageSzwTfzgjG427Bcd4WW4A4w+zhj7WIj58BY5nC8GsFvFAIiQ6PlDJrW9c=
  URL_1CV8L2:
    secure: z47uplaqZaQ0ZkroXy0GP0FOVp3qut62cSHHfMDZqwCwOnnLbDfWq0f/s82RVJNl0dS22emRlY8R1r/2dVkoMXDTPxnjV87sr9xW0JCkNyU=

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      job_name: Linux
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      job_depends_on: Linux
      job_name: Windows

matrix:
  fast_finish: true

for:
  - matrix:
      only:
        - job_name: Linux

    cache: 
      - 1cv8L1.deb
      - 1cv8L2.deb

    install:
      - ps: if (!(Test-Path 1cv8L1.deb)) { Invoke-WebRequest -Uri $env:URL_1CV8L1 -OutFile 1cv8L1.deb }
      - ps: if (!(Test-Path 1cv8L2.deb)) { Invoke-WebRequest -Uri $env:URL_1CV8L2 -OutFile 1cv8L2.deb }
      - dpkg -i 1cv8*.deb

  - matrix:
      only:
        - job_name: Windows

    cache: 
      - 1cv8t.7z

    install:
      - ps: if (!(Test-Path 1cv8t.7z)) { Invoke-WebRequest -Uri $env:URL_1CV8 -OutFile 1cv8t.7z }

    build_script:
      - 7z x 1cv8t.7z
      - mkdir database
      - bin\1cv8t CREATEINFOBASE File=%CD%/database
      - bin\1cv8t DESIGNER /F %CD%/database /LoadConfigFromFiles %CD%/config /UpdateDBCfg
      - bin\1cv8ct ENTERPRISE /F %CD%/database /C %CD%/VanessaExt.epf
      - ps: if (!(Test-Path success.txt)) { throw "Имеются ошибки" }

before_build:
  - ps: Set-Content -Path app_port.txt -Value ([uri] $env:APPVEYOR_API_URL).Port

artifacts:
  - path: autotest.log
    name: autotest log

  - path: app_port.txt
    name: app port
